
version: '3.9'

services:
    ts-node-docker:
        container_name: ts-node-docker
        build:
            context: .
            dockerfile: ./images/nodejs.dockerfile
            target: base
        volumes:
        - ./src:/app/src
        - ./nodemon.json:/app/nodemon.json
        ports:
            - "3000:3000" 
        networks:
            - example-net
        depends_on:
            - mongo
        command: npm run dev
    mongo:
        container_name: mongo
        build:
            context: .
            dockerfile: ./images/mongo.dockerfile
            target: base
        volumes:
            - ./mongo:/data/db
        ports:
            - "27017:27017" 
        networks:
            - example-net 
        # environment:
            # - MONGO_INITDB_ROOT_USERNAME=harshlinkcollect01
            # - MONGO_INITDB_ROOT_PASSWORD=harshlinkcollect01
            # - MONGO_INITDB_DATABASE=linkcollect
    nginx:
        build:
            context: .
            dockerfile: ./images/nginx.dockerfile
            target: base
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - ts-node-docker
        networks:
            - example-net

networks:
  example-net:
    external: true

volumes:
    mongo: {}
