version: '3.7'

services:

  ts-node-docker:
    build:
      target: production
    command: node build/src/app.js
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./images/configs/certbot/certbot-etc:/etc/letsencrypt
  #     - ./images/configs/certbot/certbot-var:/var/lib/letsencrypt
  #     - ./images/configs/certbot/www:/var/www/certbot
  #     - ./images/configs/web-root:/var/www/html
  #   depends_on:
  #     - nginx
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   command: certonly --webroot --webroot-path=/var/www/html --email harshsingh.eth@gmail.com --agree-tos --no-eff-email --staging -d localhost  -d dev.localhost



volumes:
  mongo: {}
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/sammy/node_project/views/
      o: bind